### ISSUE TITLE
TASK frontend functionality to edit conversation title

### ISSUE THREAD

**Issue by ErickSch** [APUOPE-RE/frontend#53]
- [ ] When a conversation is selected, it shows a "more options" button
- [x] When "more options" button is clicked it shows a dropdown menu
- [x] "more options" dropdown menu shows: Change title and Delete
- [x] Change title triggers "change title" modal
- [ ] "Change title" modal sends a POST request to backend when "save" button is clicked
- [x] Delete button triggers "are you sure" modal
- [ ] "Are you sure" modal sends a DELETE request to backend when "delete" button is clicked

**Designs:**

1. Chatbot view - "More options"  on selected conversation menu
![image](https://github.com/user-attachments/assets/dae43ec3-93e0-4569-83e6-6beb4458469c)

2. Chatbot view - "Change title" modal 
![image](https://github.com/user-attachments/assets/d27e618e-b3c6-4f61-998a-c9c11d7c3f05)

3. Chatbot view - "Are you sure" delete modal
![image](https://github.com/user-attachments/assets/8011c3aa-abcd-4329-9569-8a6720f96539)

**Comment by emilselroos** [comment]
Other parts are ready but still waiting for backend endpoints so this could be connected.
