### ISSUE TITLE
TASK Log in -page, frontend functionality

### ISSUE THREAD

**Issue by williamirva** [APUOPE-RE/frontend#9]
Under this issue frontend functionality for logging user in. UI elements are created in #2 

- [ ] Create fucntion which sends the username and password from login form to backend
- [ ] Handle the response and inform the user if login failed (invalid credentilas or some other error)
- [ ] On successful login route user to home page

Subtask of APUOPE-RE/wiki#9
Specifications: https://github.com/APUOPE-RE/Wiki/wiki/FR-%E2%80%90-Log-in-&-Registration

**Comment by roosavihlman** [comment]
Edit 1.10.2024: Updated specification link.
